server:
  port: 8080
spring:
  # 应用名称（可选）
  application:
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql:///reggie
      username: root
      password: 数据库密码
  mail:
    #默认的邮件编码为UTF-8
    default-encoding: utf-8
    # 配置smtp服务主机地址
    host: smtp.qq.com
    #发送者邮箱
    username: QQ邮箱
    #配置密码,注意不是真正的密码，而是刚刚申请到的授权码
    password: 授权码
    #端口号465或587
    port: 587
    #其他参数
    properties:
      mail:
        #配置SSL 加密工厂
        smtp:
          ssl:
            #本地测试，先放开ssl
            enable: false
            required: false
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
#        debug: true
mybatis-plus:
  configuration:
    # 在映射实体或者属性时，将数据库中表名和字段中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

reggie:
  path: 上传文件存储的路径